[package]
name = "bed-utils"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"
authors = ["Kai Zhang <kai@kzhang.org>"]

[dependencies]
num-traits = "0.2.14"
num = "0.4.0"
bio = "0.39.0"
itertools = "0.8"
indexmap = "1.7"
lexical = "6.1"
extsort = "0.4"
serde = "1.0"
bincode = "1.3"
tempfile = "3.3"

[dev-dependencies]
criterion = "0.3"
flate2 = "1.0"

[[bench]]
name = "main"
harness = false