[package]
name = "bed-utils"
version = "0.1.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]

[dependencies]
num-traits = "0.2.14"
num= "0.4.0"
noodles = { version = "0.26.0", features = ["bam", "sam"] }
noodles-bgzf = { version = "0.14.0", features = ["libdeflate"] }
bio = "0.39.0"
itertools = "0.8"
indexmap = "1.7"
lexical = "6.1"
extsort = "0.4"
serde = "1.0"
bincode = "1.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main"
harness = false